# Generated by Django 4.2.1 on 2023-06-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_rename_id_area_areacursos_idarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='fecha_creacion',
            field=models.DateField(),
        ),
    ]
