# Generated by Django 4.2.1 on 2023-06-09 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alter_cursos_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='fecha_creacion',
        ),
    ]
